#!python3
#-*- coding:utf-8 -*-#
import json
import os 
from colorama import  init, Fore, Back, Style
init(autoreset=True)
class Colored(object):
    #  前景色:红色  背景色:默认
    def red(self, s):
        return Fore.RED + s + Fore.RESET
    #  前景色:绿色  背景色:默认
    def green(self, s):
        return Fore.GREEN + s + Fore.RESET
    #  前景色:黄色  背景色:默认
    def yellow(self, s):
        return Fore.YELLOW + s + Fore.RESET

color = Colored()
print(color.red('I am red!'))
print(color.green('I am gree!'))
print(color.yellow('I am yellow!'))

def info(msg):
    print(color.green('[info]'+msg))

def error(msg):
    print(color.red('[error]' + msg))

def warn(msg):
    print(color.yellow('[warn]'+msg))

third_part = './third_part'
os.system('rm -rf %s' % third_part)
os.mkdir(third_part)


error("test error")

def getDirName(repository):
   splitlist= repository.split('/')
   return splitlist[len(splitlist)-1]

def install_rely(repository, branch, index):
    if repository is None:
        warn("""there is an error, repository not exist.
                whose index in rely.json is %d""" % count)
    if branch is None:
        branch = 'release'
    info("installing repository %s " % repository)

    os.system('cd /tmp && git clone https://%s --branch %s' % (repository, branch))
    dirName = getDirName(repository)
    os.system('rm -rf /tmp/%s/.git' % (dirName))
    os.system('mv /tmp/%s/* ./%s/' % (dirName, third_part))


f = open("./rely.json", 'r')
relys = f.read()
relyList = json.loads(relys)
index = 0

## may use multi-thread will run faster.
for rely in relyList:
    print(rely)
    install_rely(rely['repository'], rely['branch'], index)
    index = index + 1


